### ISSUE TITLE
Add mTOR1 complex

### ISSUE THREAD

**Issue by ddomingof** [johnbachman/bioentities#5]
We found "TORC1 Complex" in the SCOMP and its equivalent 0031931 in GO (http://amigo.geneontology.org/amigo/term/GO:0031931).

This term is missing in the equivalent file, should we add it?

Thank you

**Comment by johnbachman** [comment]
Yes please!

**Comment by johnbachman** [comment]
You can submit the PR at sorgerlab/famplex.

**Comment by ddomingof** [comment]
Close with PR https://github.com/sorgerlab/famplex/pull/96
